server:
  port: 9080

spring :
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3310/test1
    username: root
    password: mariadb
  # Spring Security [in-memory단 설정]
  security:
    user:
      name: tester
      password: 1234
      roles: USER, ADMIN

mybatis:
  mapper-locations: classpath:/mapper/**/*-sql.xml
  config-location: classpath:/mapper/sql-mapper-config.xml










