server:
  port: 9080
  servlet:
    jsp:
      init-parameters:
        development: true


spring :
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3310/test1
    username: root
    password: mariadb

mybatis:
  mapper-locations: classpath:/mapper/**/*-sql.xml
  config-location: classpath:/mapper/sql-mapper-config.xml







